# Generated by Django 5.1 on 2024-09-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['first_name']},
        ),
    ]
