# Generated by Django 5.1 on 2024-10-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_users_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(null=True, upload_to='user-image/'),
        ),
    ]
