# Generated by Django 5.1 on 2024-11-26 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_alter_folders_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.CharField(blank=True, choices=[], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfoldermapping',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_mappings', to='folders.documents'),
        ),
        migrations.AlterField(
            model_name='fileinfoldermapping',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_mappings', to='folders.folders'),
        ),
    ]
